listening-port=3478

fingerprint
use-auth-secret
static-auth-secret=another-super-long-random-secret-at-least-32-chars

realm=chat-turn.shopinstream.com

min-port=49160
max-port=49200

total-quota=100
bps-capacity=0

stale-nonce
no-multicast-peers
no-loopback-peers